<a href="https://colab.research.google.com/github/felwern/AI_course_exercises/blob/main/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PROJECT PUBLIC TRANSPORTATION**

All imoprts are gathered here

In [1]:
import pandas as pd
import numpy as np
import os
import glob
from google.colab import drive

#Understanding the data

In [2]:
drive.mount('/content/drive')

project_path = "/content/drive/MyDrive/fellie2026/AI/project"

print(os.listdir(project_path)) #dubble checking that the file exists

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
['transfers.csv', 'trips.csv', 'gtfs_rt_202406.csv.gz', 'service_alerts_2024.parquet', 'gtfs_rt_202407.csv.gz', 'stops.csv', 'routes.csv', 'gtfs_rt_202401.csv.gz', 'gtfs_rt_202405.csv.gz', 'gtfs_rt_202404.csv.gz', 'gtfs_rt_202403.csv.gz', 'gtfs_rt_202402.csv.gz', 'gtfs_rt_202408.csv.gz', 'gtfs_rt_202409.csv.gz', 'gtfs_rt_202410.csv.gz', 'gtfs_rt_202411.csv.gz', 'gtfs_rt_202412.csv.gz']

In [3]:
for file in os.listdir(project_path):
    full_path = os.path.join(project_path, file)

    if os.path.isfile(full_path):
        size_mb = os.path.getsize(full_path) / (1024**2)
        print(f"{file:70s} {size_mb:.2f} MB")

transfers.csv                                                          2.83 MB
trips.csv                                                              17.10 MB
gtfs_rt_202406.csv.gz                                                  301.71 MB
service_alerts_2024.parquet                                            27.69 MB
gtfs_rt_202407.csv.gz                                                  299.63 MB
stops.csv                                                              1.35 MB
routes.csv                                                             0.02 MB
gtfs_rt_202401.csv.gz                                                  327.68 MB
gtfs_rt_202405.csv.gz                                                  327.63 MB
gtfs_rt_202404.csv.gz                                                  318.96 MB
gtfs_rt_202403.csv.gz                                                  325.08 MB
gtfs_rt_202402.csv.gz                                                  306.33 MB
gtfs_rt_202408.csv.gz                                                  316.41 MB
gtfs_rt_202409.csv.gz                                                  322.42 MB
gtfs_rt_202410.csv.gz                                                  333.71 MB
gtfs_rt_202411.csv.gz                                                  309.49 MB
gtfs_rt_202412.csv.gz                                                  302.14 MB

In [ ]:
# DON'T RUN THIS CELL, the ram memory crashes :(
"""
jan_path = os.path.join(
    project_path,
    "gtfs_rt_202401.csv.gz"
)

df_jan = pd.read_csv(jan_path, sep=";")

print("Shape:", df_jan.shape)

"""

/tmp/ipykernel_9101/2209819500.py:6: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_jan = pd.read_csv(jan_path, sep=";")

In [4]:
jan_path = os.path.join(
    project_path,
    "gtfs_rt_202401.csv.gz"
)

df_sample = pd.read_csv(
    jan_path,
    sep=";",
    nrows=10000
)

print("Shape:", df_sample.shape)

display(df_sample.head())

Shape: (10000, 28)

,date,LineNumber,LineID,route_id,TransportMode,direction_id,trip_id,VehicleID,shape_id,planned_departure_sfm,...,observed_arrival_time_sfm,observed_arrival_delay,observed_arrival_uncertainty,scheduled_departure_time_sfm,observed_departure_time_sfm,observed_departure_delay,observed_departure_uncertainty,tripupdates_and_gtfs_not_merged_within_service_id,tripupdates_not_merged_with_stoptimes_or_trip,stop_headsign
0,20240101,1,9011001000100000,9011001000100000,BUS,0,14010000635988873,9.031001e+15,1014010000560262054,420,...,360.0,-60.0,0.0,420,498.0,78.0,0.0,f,f,Frihamnen
1,20240101,1,9011001000100000,9011001000100000,BUS,0,14010000635988873,9.031001e+15,1014010000560262054,420,...,540.0,80.0,0.0,460,540.0,80.0,0.0,f,f,Frihamnen
2,20240101,1,9011001000100000,9011001000100000,BUS,0,14010000635988873,9.031001e+15,1014010000560262054,420,...,578.0,84.0,0.0,494,578.0,84.0,0.0,f,f,Frihamnen
3,20240101,1,9011001000100000,9011001000100000,BUS,0,14010000635988873,9.031001e+15,1014010000560262054,420,...,660.0,60.0,0.0,600,660.0,60.0,0.0,f,f,Frihamnen
4,20240101,1,9011001000100000,9011001000100000,BUS,0,14010000635988873,9.031001e+15,1014010000560262054,420,...,711.0,49.0,0.0,662,740.0,78.0,0.0,f,f,Frihamnen

In [6]:
print("Number of rows:", len(df_sample))
print("Number of columns:", len(df_sample.columns))

print("\nColumns:")
for i, col in enumerate(df_sample.columns):
    print(f"{i}: {col}")

display(df_sample.head())

Number of rows: 10000
Number of columns: 28

Columns:
0: date
1: LineNumber
2: LineID
3: route_id
4: TransportMode
5: direction_id
6: trip_id
7: VehicleID
8: shape_id
9: planned_departure_sfm
10: planned_departure_tripupdates_sfm
11: stop_sequence
12: dist_traveled
13: previous_stop_id
14: previous_StopAreaID
15: observed_stop_id
16: observed_StopAreaID
17: scheduled_arrival_time_sfm
18: observed_arrival_time_sfm
19: observed_arrival_delay
20: observed_arrival_uncertainty
21: scheduled_departure_time_sfm
22: observed_departure_time_sfm
23: observed_departure_delay
24: observed_departure_uncertainty
25: tripupdates_and_gtfs_not_merged_within_service_id
26: tripupdates_not_merged_with_stoptimes_or_trip
27: stop_headsign

,date,LineNumber,LineID,route_id,TransportMode,direction_id,trip_id,VehicleID,shape_id,planned_departure_sfm,...,observed_arrival_time_sfm,observed_arrival_delay,observed_arrival_uncertainty,scheduled_departure_time_sfm,observed_departure_time_sfm,observed_departure_delay,observed_departure_uncertainty,tripupdates_and_gtfs_not_merged_within_service_id,tripupdates_not_merged_with_stoptimes_or_trip,stop_headsign
0,20240101,1,9011001000100000,9011001000100000,BUS,0,14010000635988873,9.031001e+15,1014010000560262054,420,...,360.0,-60.0,0.0,420,498.0,78.0,0.0,f,f,Frihamnen
1,20240101,1,9011001000100000,9011001000100000,BUS,0,14010000635988873,9.031001e+15,1014010000560262054,420,...,540.0,80.0,0.0,460,540.0,80.0,0.0,f,f,Frihamnen
2,20240101,1,9011001000100000,9011001000100000,BUS,0,14010000635988873,9.031001e+15,1014010000560262054,420,...,578.0,84.0,0.0,494,578.0,84.0,0.0,f,f,Frihamnen
3,20240101,1,9011001000100000,9011001000100000,BUS,0,14010000635988873,9.031001e+15,1014010000560262054,420,...,660.0,60.0,0.0,600,660.0,60.0,0.0,f,f,Frihamnen
4,20240101,1,9011001000100000,9011001000100000,BUS,0,14010000635988873,9.031001e+15,1014010000560262054,420,...,711.0,49.0,0.0,662,740.0,78.0,0.0,f,f,Frihamnen

In [7]:
display(df_sample.dtypes)

date                                                   int64
LineNumber                                             int64
LineID                                                 int64
route_id                                               int64
TransportMode                                         object
direction_id                                           int64
trip_id                                                int64
VehicleID                                            float64
shape_id                                               int64
planned_departure_sfm                                  int64
planned_departure_tripupdates_sfm                    float64
stop_sequence                                          int64
dist_traveled                                        float64
previous_stop_id                                       int64
previous_StopAreaID                                    int64
observed_stop_id                                       int64
observed_StopAreaID                                    int64
scheduled_arrival_time_sfm                             int64
observed_arrival_time_sfm                            float64
observed_arrival_delay                               float64
observed_arrival_uncertainty                         float64
scheduled_departure_time_sfm                           int64
observed_departure_time_sfm                          float64
observed_departure_delay                             float64
observed_departure_uncertainty                       float64
tripupdates_and_gtfs_not_merged_within_service_id     object
tripupdates_not_merged_with_stoptimes_or_trip         object
stop_headsign                                         object
dtype: object

In [8]:
missing_sample = pd.DataFrame({
    "Missing": df_sample.isna().sum(),
    "Missing %": df_sample.isna().mean() * 100
}).sort_values("Missing %", ascending=False)

display(missing_sample)

                                                   Missing  Missing %
observed_departure_uncertainty                        3393      33.93
observed_arrival_uncertainty                          3207      32.07
observed_departure_delay                              2746      27.46
observed_departure_time_sfm                           2746      27.46
observed_arrival_delay                                2744      27.44
observed_arrival_time_sfm                             2744      27.44
planned_departure_tripupdates_sfm                     2449      24.49
VehicleID                                             2449      24.49
dist_traveled                                           16       0.16
route_id                                                 0       0.00
date                                                     0       0.00
LineNumber                                               0       0.00
stop_sequence                                            0       0.00
planned_departure_sfm                                    0       0.00
shape_id                                                 0       0.00
trip_id                                                  0       0.00
TransportMode                                            0       0.00
direction_id                                             0       0.00
LineID                                                   0       0.00
previous_stop_id                                         0       0.00
observed_StopAreaID                                      0       0.00
scheduled_arrival_time_sfm                               0       0.00
previous_StopAreaID                                      0       0.00
observed_stop_id                                         0       0.00
scheduled_departure_time_sfm                             0       0.00
tripupdates_and_gtfs_not_merged_within_service_id        0       0.00
tripupdates_not_merged_with_stoptimes_or_trip            0       0.00
stop_headsign                                            0       0.00

In [9]:
jan_path = os.path.join(
    project_path,
    "gtfs_rt_202401.csv.gz"
)

# Kolumner vi behöver för första EDA:n
usecols = [
    "date",
    "LineNumber",
    "route_id",
    "direction_id",
    "trip_id",
    "observed_stop_id",
    "observed_StopAreaID",
    "stop_sequence",
    "scheduled_arrival_time_sfm",
    "observed_arrival_time_sfm",
    "observed_arrival_delay",
    "scheduled_departure_time_sfm",
    "observed_departure_time_sfm",
    "observed_departure_delay"
]

total_rows = 0
delay_values = []
line_counts = {}
stop_counts = {}
date_counts = {}

for chunk in pd.read_csv(
    jan_path,
    sep=";",
    usecols=usecols,
    chunksize=100_000
):

    total_rows += len(chunk)

    # Spara bara delay-värdena
    arrival_delay = chunk["observed_arrival_delay"].dropna()
    delay_values.extend(arrival_delay.tolist())

    # Antal observationer per linje
    counts = chunk["LineNumber"].value_counts()
    for line, count in counts.items():
        line_counts[line] = line_counts.get(line, 0) + count

    # Antal observationer per hållplats
    counts = chunk["observed_stop_id"].value_counts()
    for stop, count in counts.items():
        stop_counts[stop] = stop_counts.get(stop, 0) + count

    # Antal observationer per datum
    counts = chunk["date"].value_counts()
    for date, count in counts.items():
        date_counts[date] = date_counts.get(date, 0) + count


print("Total rows:", total_rows)
print("Number of delay observations:", len(delay_values))
print("Number of lines:", len(line_counts))
print("Number of stops:", len(stop_counts))
print("Number of dates:", len(date_counts))

/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1111037777.py:30: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(

Totalt antal rader: 18659047
Antal delay-observationer: 17708003
Antal linjer: 900
Antal hållplatser: 11652
Antal datum: 31

In [11]:

delay_array = np.array(delay_values)

print("Mean delay:", np.mean(delay_array))
print("Median delay:", np.median(delay_array))
print("Std:", np.std(delay_array))
print("Min:", np.min(delay_array))
print("Max:", np.max(delay_array))

print("\nPercentiles:")
for p in [1, 5, 25, 50, 75, 90, 95, 99]:
    print(f"{p}th percentile:", np.percentile(delay_array, p))

Mean delay: 131.77758852875732
Median delay: 91.0
Std: 253.32730881763817
Min: -9741.0
Max: 11610.0

Percentiles:
1th percentile: -284.0
5th percentile: -89.0
25th percentile: 9.0
50th percentile: 91.0
75th percentile: 200.0
90th percentile: 351.0
95th percentile: 492.0
99th percentile: 939.0

In [12]:
bins = [
    -np.inf,
    -600,
    -300,
    -120,
    -60,
    0,
    60,
    120,
    300,
    600,
    1200,
    1800,
    3600,
    np.inf
]

labels = [
    "< -10 min",
    "-10 to -5 min",
    "-5 to -2 min",
    "-2 to -1 min",
    "-1 to 0 min",
    "0 to 1 min",
    "1 to 2 min",
    "2 to 5 min",
    "5 to 10 min",
    "10 to 20 min",
    "20 to 30 min",
    "30 to 60 min",
    "> 60 min"
]

delay_counts = pd.Series(0, index=labels)

for chunk in pd.read_csv(
    jan_path,
    sep=";",
    usecols=["observed_arrival_delay"],
    chunksize=100_000
):

    delays = chunk["observed_arrival_delay"].dropna()

    categories = pd.cut(
        delays,
        bins=bins,
        labels=labels,
        right=False
    )

    counts = categories.value_counts()

    delay_counts = delay_counts.add(counts, fill_value=0)


delay_counts = delay_counts.astype(int)

print(delay_counts)
print()
print("Total:", delay_counts.sum())

-1 to 0 min      2174841
-10 to -5 min     131786
-2 to -1 min      766819
-5 to -2 min      442361
0 to 1 min       3537827
1 to 2 min       3182006
10 to 20 min      481572
2 to 5 min       5068290
20 to 30 min       57132
30 to 60 min       23190
5 to 10 min      1806979
< -10 min          29832
> 60 min            5368
dtype: int64

Total: 17708003

In [13]:
hour_stats = []

for chunk in pd.read_csv(
    jan_path,
    sep=";",
    usecols=[
        "scheduled_arrival_time_sfm",
        "observed_arrival_delay"
    ],
    chunksize=100_000
):

    chunk = chunk.dropna(subset=["observed_arrival_delay"])

    # Convert seconds from midnight to hour
    chunk["hour"] = (
        chunk["scheduled_arrival_time_sfm"] // 3600
    ).astype(int)

    stats = chunk.groupby("hour")["observed_arrival_delay"].agg(
        count="count",
        mean="mean",
        median="median"
    )

    hour_stats.append(stats)


# Combine all chunks
hour_stats = pd.concat(hour_stats)

hour_stats = hour_stats.groupby(level=0).agg(
    count=("count", "sum"),
    mean=("mean", "mean"),
    median=("median", "median")
)

hour_stats = hour_stats.sort_index()

print(hour_stats)

        count        mean  median
hour
-1        126  -57.300000    0.00
 0     238878   78.651045   66.00
 1     182478  108.201328   88.00
 2     124359  140.759787  110.00
 3      99700  139.587658  113.75
 4     135559  114.527866   95.00
 5     437525  101.529776   88.00
 6     908646  118.192570   94.00
 7    1166144  128.297292   95.00
 8    1100120  150.032424   97.00
 9     928756  127.065782   81.00
 10    870077  100.990309   74.00
 11    871249  103.933750   81.00
 12    881963  118.392288   91.00
 13    915450  125.382325   90.00
 14   1012274  134.137837   96.00
 15   1157399  154.359559  107.00
 16   1214531  185.142561  130.00
 17   1208084  179.440629  123.00
 18   1049199  141.499167   95.00
 19    806002  117.453894   85.00
 20    683413  109.509830   87.00
 21    616416  102.323472   80.00
 22    533052   95.728738   76.00
 23    464476   84.917557   68.00
 24    100887   73.775249   51.00
 25      1240   65.137624    1.00

In [14]:
for chunk in pd.read_csv(
    jan_path,
    sep=";",
    usecols=["scheduled_arrival_time_sfm"],
    chunksize=100_000
):

    unusual = chunk[
        (chunk["scheduled_arrival_time_sfm"] < 0) |
        (chunk["scheduled_arrival_time_sfm"] >= 86400)
    ]

    if len(unusual) > 0:
        print(unusual["scheduled_arrival_time_sfm"].describe())
        print(unusual["scheduled_arrival_time_sfm"].head(20))
        break

count      652.000000
mean     87118.989264
std        643.902265
min      86400.000000
25%      86639.000000
50%      86940.000000
75%      87451.750000
max      89580.000000
Name: scheduled_arrival_time_sfm, dtype: float64
2842    86520
2843    86573
2844    86650
2845    86700
2846    86819
2847    86905
2848    86947
2849    87013
2850    87063
2851    87180
2860    86427
2861    86520
2862    86585
2863    86641
2864    86693
2865    86808
2866    86940
2867    86986
2868    87060
2869    87105
Name: scheduled_arrival_time_sfm, dtype: int64

In [15]:
for chunk in pd.read_csv(
    jan_path,
    sep=";",
    usecols=["scheduled_arrival_time_sfm"],
    chunksize=100_000
):

    unusual = chunk[
        chunk["scheduled_arrival_time_sfm"] < 0
    ]

    if len(unusual) > 0:
        print(unusual["scheduled_arrival_time_sfm"].describe())
        print(unusual["scheduled_arrival_time_sfm"].head(20))
        break

count      1.0
mean    -180.0
std        NaN
min     -180.0
25%     -180.0
50%     -180.0
75%     -180.0
max     -180.0
Name: scheduled_arrival_time_sfm, dtype: float64
156298   -180
Name: scheduled_arrival_time_sfm, dtype: int64

the lines

In [16]:
line_stats = []

for chunk in pd.read_csv(
    jan_path,
    sep=";",
    usecols=[
        "LineNumber",
        "observed_arrival_delay"
    ],
    chunksize=100_000
):

    # Remove rows without delay
    chunk = chunk.dropna(subset=["observed_arrival_delay"])

    # Statistics per line within this chunk
    stats = chunk.groupby("LineNumber")["observed_arrival_delay"].agg(
        count="count",
        sum="sum",
        sum_sq=lambda x: (x ** 2).sum()
    )

    line_stats.append(stats)


# Combine chunks
line_stats = pd.concat(line_stats)

# Aggregate counts and sums
line_stats = line_stats.groupby(level=0).agg(
    count=("count", "sum"),
    sum=("sum", "sum"),
    sum_sq=("sum_sq", "sum")
)

# Calculate mean and standard deviation
line_stats["mean_delay"] = line_stats["sum"] / line_stats["count"]

line_stats["std_delay"] = np.sqrt(
    (line_stats["sum_sq"] / line_stats["count"])
    - line_stats["mean_delay"] ** 2
)

# Remove helper columns
line_stats = line_stats[
    ["count", "mean_delay", "std_delay"]
]

# Sort by mean delay
line_stats = line_stats.sort_values(
    "mean_delay",
    ascending=False
)

print(line_stats.head(20))

/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/1336654626.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(

            count   mean_delay    std_delay
LineNumber
908          1245  7638.538153  3326.401826
908           215  7620.362791  3083.849722
955           154  2947.909091  2748.527954
955          2434  2415.261298  2436.261824
952           456  1907.598684  1127.229103
952          4741  1882.337271  1486.467565
12             11   983.727273   801.839260
699           439   625.790433   427.662025
83            726   560.184573   570.017308
698           202   557.282178   504.790197
72            868   535.842166   462.284120
592          4064   505.746555  1611.149044
598          1602   503.166667   355.988440
8             400   488.827500   674.610423
54            490   483.434694   483.717253
698          1000   430.979000   471.443492
574         14889   398.510108   776.756209
574           839   389.625745   884.763697
598          7005   382.943183   380.303133
556          6642   379.232761   370.310081

In [17]:
print(line_stats.tail(20))

             count  mean_delay   std_delay
LineNumber
176E           136  -24.066176  364.936683
817           2156  -25.175325  159.947246
496            204  -29.627451  140.111330
19          225854  -30.006602  135.386862
889           1860  -30.908065  233.089082
18           24262  -31.319471  126.058292
31           21956  -34.763482   75.397670
17           59444  -38.650898  165.658174
19            6380  -40.120846  106.132325
31            2604  -42.983103   42.458823
17          113288  -43.349684  150.032622
20             296  -47.510135  718.385549
11           51286  -54.954607  129.845528
11           45298  -56.601881  128.127632
23             819  -59.968254   98.930676
10           59035  -63.286576  147.898169
10           44182  -70.096374  168.810412
968            392  -76.313776  261.195321
968           3920  -93.445663  201.612337
34             106 -113.981132  608.841197

In [18]:
rows_908 = []

for chunk in pd.read_csv(
    jan_path,
    sep=";",
    usecols=[
        "LineNumber",
        "LineID",
        "route_id",
        "TransportMode",
        "direction_id",
        "observed_arrival_delay"
    ],
    chunksize=100_000
):

    chunk = chunk[
        (chunk["LineNumber"] == 908) &
        (chunk["observed_arrival_delay"].notna())
    ]

    rows_908.append(chunk)

line908 = pd.concat(rows_908)

print(line908.groupby(
    ["LineNumber", "LineID", "route_id", "TransportMode", "direction_id"]
)["observed_arrival_delay"].agg(
    ["count", "mean", "median"]
).sort_values("mean", ascending=False))

/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(
/tmp/ipykernel_9677/2384458965.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.

                                                                         count  \
LineNumber LineID           route_id         TransportMode direction_id
908        9011001090800000 9011001090800000 BUS           1               215

                                                                                mean  \
LineNumber LineID           route_id         TransportMode direction_id
908        9011001090800000 9011001090800000 BUS           1             7620.362791

                                                                         median
LineNumber LineID           route_id         TransportMode direction_id
908        9011001090800000 9011001090800000 BUS           1             9088.0

In [19]:
transport_modes = []

for chunk in pd.read_csv(
    jan_path,
    sep=";",
    usecols=["TransportMode"],
    chunksize=100_000
):
    transport_modes.append(chunk["TransportMode"].value_counts())

transport_modes = pd.concat(transport_modes).groupby(level=0).sum()

print(transport_modes)

TransportMode
BUS      16443319
METRO     1199824
SHIP        66527
TRAIN      288119
TRAM       661258
Name: count, dtype: int64

# Descriptive analysis

# Problem Formulation

# Model Development

# Diagnostics